baseURL = "https://shimo5.me/"
DefaultContentLanguage = "en" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "en-us"
title = "shimo"
copyright = "&copy; 2019. All rights reserved."
theme = "diary"
googleAnalytics = "UA-145833063-1"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "エンジニアの中の人"
enableGitalk = true
favicon = "/images/favicon.ico"

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "Shimo's Blog"
description = "都内でエンジニアやってます。カフェ巡りとプログラミングが趣味です。たまにホテル巡りも、聖人発達理論やメタ認知なんかもかじってます。"

[params.gitalk]
  owner = "shimonosatoru"
  repo = "gitalk-comments-store"
  client_id = "1bfaa38e77291c664283"
  client_secret = "83b14049070475e338810e9592bcc9dab426c090"
[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/post"
name = "Archive"
weight = 1
[[menu.main]]
url = "/categories"
name = "Categories"
weight = 2
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 4
[[menu.main]]
url = "https://twitter.com/shimo5_me"
name = "Twitter"
weight = 5
[[menu.main]]
url = "https://facebook.com/shimonosatoru"
name = "Facebook"
weight = 6
[[menu.main]]
url = "https://github.com/shimonosatoru"
name = "GitHub"
weight = 7
[[menu.main]]
url = "https://www.linkedin.com/in/shimonosatoru/"
name = "LinkedIn"
weight = 8